---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-ts
  name: backend-ts
  namespace: trivia-together
spec:
  type: NodePort
  ports:
    - nodePort: 30010
      port: 3000
  selector:
    service: backend-ts

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-admin-react
  name: frontend-admin-react
  namespace: trivia-together
spec:
  type: NodePort
  ports:
    - nodePort: 30030
      port: 3000
  selector:
    service: frontend-admin-react

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-client-react
  name: frontend-client-react
  namespace: trivia-together
spec:
  type: NodePort
  ports:
    - nodePort: 30020
      port: 3000
  selector:
    service: frontend-client-react

---
apiVersion: v1
kind: Namespace
metadata:
  name: trivia-together
  namespace: trivia-together

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-ts
  name: backend-ts
  namespace: trivia-together
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-ts
  template:
    metadata:
      labels:
        service: backend-ts
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: thephen/tt-backend-ts:v0.0.0
          name: backend-ts
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend-admin-react
  name: frontend-admin-react
  namespace: trivia-together
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-admin-react
  template:
    metadata:
      labels:
        service: frontend-admin-react
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: thephen/tt-frontend-admin-react:v0.0.0
          name: frontend-admin-react
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend-client-react
  name: frontend-client-react
  namespace: trivia-together
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-client-react
  template:
    metadata:
      labels:
        service: frontend-client-react
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: thephen/tt-frontend-client-react:v0.0.0
          name: frontend-client-react
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always

