# version: '3.8'
services:
  backend-node-ts:
    image: thephen/tt-backend-node-ts:v0.0.0
    environment:
      NODE_ENV: production
    ports:
      - "3010:3000"
  frontend-client-react:
    image: thephen/tt-frontend-client-react:v0.0.0
    environment:
      NODE_ENV: production
    ports:
      - "3020:3000"
  frontend-admin-react:
    image: thephen/tt-frontend-admin-react:v0.0.0
    environment:
      NODE_ENV: production
    ports:
      - "3030:3000"
